### ISSUE TITLE
Where can I find google playstore's uid?

### ISSUE THREAD

**Issue by amosbird** [Magisk-Modules-Repo/v2ray#10]
我在 `/data/system/packages.list` 里没有看到相关的playstore项, 请问如果要让playstore走v2ray应该如何配置呢?

**Comment by chendefine** [comment]
关于appid怎么查，可以借助其他软件比如shadowsocks的分应用代理页面，括号括的数字就是appid
shadowsocks-appuid
![image](https://user-images.githubusercontent.com/4407281/59582175-f2750800-9109-11e9-9e90-c9c0c7ee6bd8.png)

**Comment by amosbird** [comment]
谢谢
