### ISSUE TITLE
输入v2ray提示config不存在

### ISSUE THREAD

**Issue by RezaFeng** [Magisk-Modules-Repo/v2ray#12]
OnePlus7Pro:/ # v2ray
V2Ray 4.18.0 (Po) 20190228
A unified platform for anti-censorship.
main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

**Comment by chendefine** [comment]
`export V2RAY_LOCATION_ASSET=/data/v2ray; v2ray -test -config /data/v2ray/config.json`
