### ISSUE TITLE
貌似是跳過中國IP代理？

### ISSUE THREAD

**Issue by friskde** [Magisk-Modules-Repo/v2ray#17]
可否設置為全局IP代理呢？

**Comment by whyou** [comment]
请参考 v2ray.com 自行修改配置文件。

**Comment by friskde** [comment]
> 请参考v2ray.com自行修改配置文件。

嗯谢谢，已经解决了，还想问一下黑名单模式如何设置呢？

**Comment by whyou** [comment]
请参考以下链接。
https://toutyrater.github.io/basic/routing/adblock.html

**Comment by friskde** [comment]
> 请参考以下链接[.https：](https://toutyrater.github.io/basic/routing/adblock.html) //toutyrater.github.io/basic/routing/adblock.html
> [](https://toutyrater.github.io/basic/routing/adblock.html)

不好意思没说清楚，是appid.list的指定app的黑名单

**Comment by chendefine** [comment]
参考: https://github.com/Magisk-Modules-Repo/v2ray/issues/2

**Comment by friskde** [comment]
> 参考：[＃2](https://github.com/Magisk-Modules-Repo/v2ray/issues/2)

哦哦学会了，非常感谢
