### ISSUE TITLE
关于透明代理的分应用代理

### ISSUE THREAD

**Issue by whyou** [Magisk-Modules-Repo/v2ray#2]
能否将现在的白名单类型扩展为可选白名单或黑名单类型？

**Comment by chendefine** [comment]
这个可以做，迟点有空加这个功能。

**Comment by chendefine** [comment]
@whyou 已更新分应用代理的脚本，支持白名单或黑名单代理应用: https://github.com/Magisk-Modules-Repo/v2ray/commit/455b28654f4cd32ed9935e688123b29cffbeaaa9

更新后，可以在`appid.list`文件的第一行加 `# bypass` 切换成绕行模式，除了`appid.list`指定的app以外，模块会代理其他所有应用。
此外，若不加 `# bypass` ，则模块只会代理`appid.list`中指定的app，与之前的版本一样。
