### ISSUE TITLE
三星s8安装后没法连接服务器

### ISSUE THREAD

**Issue by jhl601408785** [Magisk-Modules-Repo/v2ray#3]
折腾的半天发现用不了，求大神帮助。
手机service.log
V2Ray 4.18.0 (Po) 20190228 A unified platform for anti-censorship. Configuration OK. [Info]: Starting v2ray service.
[Info]: v2ray service is running. ( PID: 3893 ) 
[Info]: Clean nat proxy iptables rules.
[Info]: Create proxy iptables chains. 
[Info]: Proxy softap0 WiFi guest's TCP network. 
[Info]: Block illegal visit. 

配置：
// Config file of V2Ray. This file follows standard JSON format, with comments support.
// Uncomment entries below to satisfy your needs. Also read our manual for more detail at
// https://www.v2ray.com/
{
  "log": {
    // By default, V2Ray writes access log to stdout.
    // "access": "/path/to/access/log/file",

    // By default, V2Ray write error log to stdout.
    // "error": "/path/to/error/log/file",
    "error": "/data/v2ray/run/error.log",

    // Log level, one of "debug", "info", "warning", "error", "none"
    "loglevel": "warning"
  },
  // List of inbound proxy configurations.
  "inbounds": [{
    // Port to listen on. You may need root access if the value is less than 1024.
    "port": 65535,

    // IP address to listen on. Change to "0.0.0.0" to listen on all network interfaces.
    "listen": "0.0.0.0",

    // Tag of the inbound proxy. May be used for routing.
    "tag": "proxy-inbound",

    // Protocol name of inbound proxy.
    "protocol": "dokodemo-door",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
      "timeout": 10,
      "network": "tcp,udp",
      "followRedirect": true
    },

    // Enable sniffing on TCP connection.
    "sniffing": {
      "enabled": true,
      // Target domain will be overriden to the one carried by the connection, if the connection is HTTP or HTTPS.
      "destOverride": ["http", "tls"]
    }
  }],
  // List of outbound proxy configurations.
  "outbounds": [{
    // Replace your proxy protocol in this section, like: vmess or shadowsocks
    "protocol": "vmess",

    // Settings of the protocol. Varies based on protocol.
    "settings": {
		"vnext": [
          {
            "address": "xx.7x.xx9.6x",
            "port": 50xx0,
            "users": [
              {
                "id": "27843239-7e62-2454-5td3-098a63964b6b",
                "alterId": 4,
                "security": "auto",
                "level": 0
              }
            ]
          }
        ]
	},
	 "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {
          "serverName": "",
          "allowInsecure": false
        },
        "tcpSettings": {
          "header": {
            "type": "none",
            "request": {}
          }
        }
      },
    "mux": {
        "enabled": true,
        "concurrency": 8
      },
    // Tag of the outbound. May be used for routing.
    "tag": "proxy"
  },
  {
    // Protocol name of the outbound proxy.
    "protocol": "freedom",

    // Settings of the protocol. Varies based on protocol.
    "settings": {},

    // Tag of the outbound. May be used for routing.
    "tag": "direct"
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],

  // Transport is for global transport settings. If you have multiple transports with same settings
  // (say mKCP), you may put it here, instead of in each individual inbound/outbounds.
  //"transport": {},

  // Routing controls how traffic from inbounds are sent to outbounds.
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules":[
      {
        // Bypass private IPs.
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "direct"
      },
      {
        // Bypass all china IPs.
        "type": "field",
        "ip": ["geoip:cn"],
        "outboundTag": "direct"
      },
      {
        // Bypass all china sites.
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },
      {
        // Blocks major ads.
        "type": "field",
        "domain": ["geosite:category-ads"],
        "outboundTag": "blocked"
      }
    ]
  },

  // Dns settings for domain resolution.
  "dns": {
    // Static hosts, similar to hosts file.
    "hosts": {
      // Match v2ray.com to another domain on CloudFlare. This domain will be used when querying IPs for v2ray.com.
      "domain:v2ray.com": "www.vicemc.net",

      // The following settings help to eliminate DNS poisoning in mainland China.
      // It is safe to comment these out if this is not the case for you.
      "domain:github.io": "pages.github.com",
      "domain:wikipedia.org": "www.wikimedia.org",
      "domain:shadowsocks.org": "electronicsrealm.com"
    },
    "servers": [
      "1.1.1.1",
      {
        "address": "114.114.114.114",
        "port": 53,
        // List of domains that use this DNS first.
        "domains": [
          "geosite:cn"
        ]
      },
      "8.8.8.8",
      "localhost"
    ]
  },

  // Policy controls some internal behavior of how V2Ray handles connections.
  // It may be on connection level by user levels in 'levels', or global settings in 'system.'
  "policy": {
    // Connection policys by user levels
    "levels": {
      "0": {
        "uplinkOnly": 0,
        "downlinkOnly": 0
      }
    },
    "system": {
      "statsInboundUplink": false,
      "statsInboundDownlink": false
    }
  },

  // Stats enables internal stats counter.
  // This setting can be used together with Policy and Api. 
  //"stats":{},

  // Api enables gRPC APIs for external programs to communicate with V2Ray instance.
  //"api": {
    //"tag": "api",
    //"services": [
    //  "HandlerService",
    //  "LoggerService",
    //  "StatsService"
    //]
  //},

  // You may add other entries to the configuration, but they will not be recognized by V2Ray.
  "other": {}
}

现象：
通过手机上的Termux可以看到v2ray已经运行，检测config.json配置也是对的，但是在服务器端看不到有ip连接的日志。我用v2ray的客户端进行连接是有ip连接的日志的。

**Comment by chendefine** [comment]
看服务日志你是没指定要代理的app啊。
v2ray的magisk模块推荐的用法是把你想用v2ray代理的app的uid写到`/data/v2ray/appid.list`文件里，这样启动模块时就能代理你指定的app了。如果你想代理所有app那就写一个0进去就好了。

关于appid怎么查，可以借助其他软件比如shadowsocks的分应用代理页面，括号括的数字就是appid
![shadowsocks-appuid](https://user-images.githubusercontent.com/4407281/56508630-57bbdb00-6557-11e9-904b-78e362ad80b2.png)

遇到问题，建议先看下首页的文档，里面已经教你怎么使用了。

**Comment by jhl601408785** [comment]
appid.list已经写了uid,也是根据你的方法从packages.list里面找的，不知道为什么没生效。写零也试过，都不好使，会不会是Android 9.0的原因，还有就是我安装好后/data/v2ray/下是没有appid.list，是我自己创建的。

**Comment by chendefine** [comment]
我刚刚试了一下写0到appid.list是有个bug的确有问题，我改了。
但是你的情况可能是没读取到appid.list文件的内容，可能要麻烦你在终端执行一下
`sh -x /sbin/.magisk/img/v2ray/scripts/v2ray.tproxy enable &> /data/v2ray/run/debug.log` 
然后收取一下debug.log日志我分析一下原因。

**Comment by jhl601408785** [comment]
[debug.log](https://github.com/Magisk-Modules-Repo/v2ray/files/3105746/debug.log)

**Comment by chendefine** [comment]
debug日志看到好像你的appid.list文件是空的啊…
终端里 `cat /data/v2ray/appid.list` 会有输出吗？
莫非Android 9.0的挂载命名空间连data目录都隔离了 T_T

**Comment by jhl601408785** [comment]
![微信图片_20190423124551](https://user-images.githubusercontent.com/46816158/56554891-bcae1a00-65c5-11e9-9769-ed71fa206bb8.jpg)
可以输出。

**Comment by chendefine** [comment]
看不出问题，不知道方不方便把appid.list发给我来试试看？

**Comment by jhl601408785** [comment]
可以，我觉的无论是否我手机的应用程序能不能代理，但是我手机上的outbound应该先会和服务器端的inbound建立连接才是，我通过服务器的日志没发现两者建立连接了。这个也和applist有关（小白一个不是太懂）
[appid.zip](https://github.com/Magisk-Modules-Repo/v2ray/files/3105887/appid.zip)

**Comment by chendefine** [comment]
破案了，你写的这个appid.list一整行没有`\n`这个字符结尾，所以shell在执行read的时候无法识别文本内容。
解决方案是执行一下`echo "" >> /data/v2ray/appid.list` 这样给一整行添加了一个结尾，脚本就能识别了，我试成功了，你试下看。

**Comment by chendefine** [comment]
@jhl601408785 关于没有结束符的这种特殊情况现在已经在最新版本 https://github.com/Magisk-Modules-Repo/v2ray/commit/6ca8237ac2cdd28691b6ac17ea8314d795f157b2 的脚本里面处理了，升级即可。

**Comment by jhl601408785** [comment]
刚测试了一下，现在可以了，谢谢大神。

**Comment by chendefine** [comment]
不客气，也谢谢你提交bug
