### ISSUE TITLE
Please fix the download script

### ISSUE THREAD

**Issue by coreze** [Magisk-Modules-Repo/v2ray#47]
change
curl -s -I "${official_v2ray_link}/latest" | grep **Location** | grep -o "tag.*" | grep -o "v[0-9.]*"
to
curl -s -I "${official_v2ray_link}/latest" | grep **location** | grep -o "tag.*" | grep -o "v[0-9.]*"

**Comment by cyberblood** [comment]
> 
> 
> change
> curl -s -I "${official_v2ray_link}/latest" | grep **Location** | grep -o "tag._" | grep -o "v[0-9.]_"
> to
> curl -s -I "${official_v2ray_link}/latest" | grep **location** | grep -o "tag._" | grep -o "v[0-9.]_"

Thanks ! bug fixed.
