### ISSUE TITLE
无法自启动 Magisk 20.4,V2Ray V4.20.0

### ISSUE THREAD

**Issue by NNorLand** [Magisk-Modules-Repo/v2ray#52]
安卓版本：9.0
magisk版本：20.4（20400）
magisk manager版本：7.5.1
v2ray for Android 版本：v4.20.0
安装完模块，配置好，重启手机，模块不能自启动，使用`v2ray.service start`和`v2ray.tproxy enable`手动启动之后，外网访问正常。
magisk日志如下：

--------- beginning of main
--------- beginning of system
05-17 07:20:44.066   647   647 I Magisk  : Magisk 20.4(20400) daemon started
05-17 07:20:44.066   647   647 I Magisk  : * Device API level: 28
05-17 07:20:44.091   647   648 I Magisk  : ** post-fs-data mode running
05-17 07:20:44.093   647   648 I Magisk  : * Initializing Magisk environment
05-17 07:20:44.113   647   648 I Magisk  : * Mounting mirrors
05-17 07:20:44.113   647   648 I Magisk  : mount: /sbin/.magisk/mirror/system
05-17 07:20:44.113   647   648 I Magisk  : mount: /sbin/.magisk/mirror/vendor
05-17 07:20:44.113   647   648 I Magisk  : mount: /sbin/.magisk/mirror/data
05-17 07:20:44.114   647   648 I Magisk  : link: /sbin/.magisk/mirror/product
05-17 07:20:44.114   647   648 I Magisk  : * Setting up internal busybox
05-17 07:20:44.127   647   648 I Magisk  : * Running post-fs-data.d scripts
05-17 07:20:44.303   647   648 I Magisk  : * Running module post-fs-data scripts
05-17 07:20:44.303   647   648 I Magisk  : taichi: exec [post-fs-data.sh]
05-17 07:20:44.308   647   648 I Magisk  : scene_systemless: exec [post-fs-data.sh]
05-17 07:20:44.311   647   648 I Magisk  : * Loading modules
05-17 07:20:44.311   647   648 I Magisk  : v2ray: constructing magic mount structure
05-17 07:20:44.312   647   648 I Magisk  : taichi: loading [system.prop]
05-17 07:20:44.315   647   648 I Magisk  : taichi: constructing magic mount structure
05-17 07:20:44.316   647   648 I Magisk  : scene_systemless: loading [system.prop]
05-17 07:20:44.318   647   648 I Magisk  : scene_systemless: constructing magic mount structure
05-17 07:20:44.320   647   648 I Magisk  : busybox-ndk: constructing magic mount structure
05-17 07:20:44.322   647   648 I Magisk  : mnt_tmpfs : /system/bin
05-17 07:20:44.322   647   648 I Magisk  : bind_mount: /system/bin/app_process64
05-17 07:20:44.322   647   648 I Magisk  : copy_link : /system/bin/false
....more bind_mount,copy_link
05-17 07:20:44.419   647   658 I Magisk  : * Starting MagiskHide
05-17 07:20:44.420   647   658 I Magisk  : hide_policy: Hiding sensitive props
05-17 07:20:44.420   647   658 I Magisk  : hide_list init: [cn.oneplus.wallet/cn.oneplus.wallet]
...more hide_list
03-29 11:27:05.138   647   993 I Magisk  : ** late_start service mode running
03-29 11:27:05.138   647   993 I Magisk  : * Running service.d scripts
03-29 11:27:05.139   647   993 I Magisk  : * Running module service scripts
03-29 11:27:05.139   647   993 I Magisk  : v2ray: exec [service.sh]
03-29 11:27:05.140   647   993 I Magisk  : taichi: exec [service.sh]
03-29 11:27:05.179   647   993 I Magisk  : scene_systemless: exec [service.sh]
03-29 11:27:05.249   647   658 I Magisk  : hide_list init: [com.excean.gspace.b64/com.excean.gspace.b64:platform.gameplugin3.P01]
...more hide_list
03-29 11:27:20.591   647  4404 I Magisk  : ** boot_complete triggered
03-29 11:27:48.683   647   658 I Magisk  : proc_monitor: [com.oneplus.card] PID=[17866] UID=[10172]
...more proc_monitor

v2ray 手动启动输出如下：
:/data/data/com.termux/files/home # /sbin/.magisk/img/v2ray/scripts/v2ray.service start
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm64)
A unified platform for anti-censorship.
2020/03/29 03:32:35 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /data/v2ray/config.json
Configuration OK.
[Info]: Starting v2ray service.
[Info]: v2ray service is running. ( PID: 26429 )
:/data/data/com.termux/files/home # /sbin/.magisk/img/v2ray/scripts/v2ray.tproxy enable
[Info]: Clean nat proxy iptables rules.
[Info]: Create proxy iptables chains.
[Info]: Proxy com.microsoft.emmx APP's network.
[Info]: Proxy com.android.vending APP's network.
[Info]: Proxy com.yg9XRcwJXHG5.tEh APP's network.
[Info]: Proxy org.telegram.messenger APP's network.
[Info]: Proxy softap0 WiFi guest's TCP network.
[Info]: Block illegal visit.

**Comment by mreazo** [comment]
俺也一样，，手动重启不能访问外网，重装v2ray也不能访问外网，最好俺降回.3就可以访问外网 了

**Comment by wyUshio** [comment]
问下安装失败 连接不上 已经安装了 curl的模块。。

**Comment by lyq1996** [comment]
看起来像magisk更新之后，出现的问题。。我手动都启动不了。。
```
sbin/.magisk/img/v2ray/scripts/v2ray.service start               <
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm64)
A unified platform for anti-censorship.
2020/03/30 01:59:00 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /data/v2ray/config.json
main: failed to create server > v2ray.com/core/app/log: failed to initialize error logger > open /data/v2ray/run/error.log: permission denied
2|:/ $
```
安装也报错，后面我修改了下脚本，本地安装v2ray-linux-arm64.zip才安装上…

**Comment by whyou** [comment]
最新的版本更新了启动运行的方式，修复了此问题。

**Comment by NNorLand** [comment]
> 最新的版本更新了启动运行的方式，修复了此问题。

感谢大佬的付出。在仓库更新后，重启手机，已经可以自启了。
