### ISSUE TITLE
v2ray 4.27更改了zip名称,导致无法成功下载

### ISSUE THREAD

**Issue by HiFiPhile** [Magisk-Modules-Repo/v2ray#64]
如题

v2ray-linux-arm64.zip改成了v2ray-linux-arm64-v8a.zip

**Comment by Jason-2048** [comment]
临时解决方法：
下载zip安装包，修改里面的 customize.sh ，把原先的 v2ray-linux-arm64.zip 修改成 v2ray-linux-arm64-v8a.zip ，保存，重新安装，就行了

**Comment by Jason-2048** [comment]
如果以后 v2ray-core 停止更新，你也可以同样方法改为 v2fly-core  。
至于第一次安装，修改 config.json ，重启之后，部分程序不能正常代理的，重启一下就行了。

**Comment by HiFiPhile** [comment]
现在我就是这样改的，不知道文件名之后还会不会再改。

**Comment by RPRX** [comment]
> 
> 
> 现在我就是这样改的，不知道文件名之后还会不会再改。

应该不会再改了
