### ISSUE TITLE
magisk v2ray问题

### ISSUE THREAD

**Issue by xiaosong9998** [Magisk-Modules-Repo/v2ray#69]
你好大神，小白求教。之前模块配置后都能正常用，自从删掉再重新安装配置好后就不能用了，data/v2ray文件夹里appid.list文件也没有了！想问下怎么回事？
![Screenshot_20200813-235653](https://user-images.githubusercontent.com/69465847/90157741-b1858b80-ddc0-11ea-8077-6f8c24e07d52.jpg)

**Comment by lodylee** [comment]
同样的问题，求解

**Comment by RPRX** [comment]
#65 Fixed.

**Comment by xiaosong9998** [comment]
8月16号的新版本已经修复好bug，可以正常使用了
