### ISSUE TITLE
请问如何禁用 dnscrypt-proxy？

### ISSUE THREAD

**Issue by jslll135** [Magisk-Modules-Repo/v2ray#74]
内置 dnscrypt-proxy 对我而言并无用处。如果我需要使用 dnscrypt-proxy，magisk 有单独的模块，可以更方便地配置。v2ray 本身支持 DoH 足以满足大部分需求，且可以使用 v2ray 内置的大量域名列表。此模块内置 dnscrypt-proxy 徒增体积，复杂性和耗电量。请问是否有禁用的选项？

**Comment by whyou** [comment]
我想你可以使用上个版本。每次需要更新时手动重新安装本地的模块即可更新二进制文件。

**Comment by whalechoi** [comment]
直接删掉dnscrypt-proxy的配置文件即可禁用，在乎体积可以修改安装包，引入dnscrypt-proxy的初衷是为了更好的解决内网污染（被污染成0.0.0.0等 #60  ），先前版本（20200326，ps：20200611是一个错误的修改 #68 ）将dns请求直接dnat到65534的dokodemo-door确实解决了这种内网污染，但是域名在进入v2ray内置dns服务器之前会走代理查询一遍，这无形的增加了dns解析时间，并且存在dns解析泄露风险；远古版本（未引入dns keeper之前），则对这种内网污染束手无策。

**Comment by jslll135** [comment]
> 我想你可以使用上个版本

我目前是这么解决的。但上游可能会发生变化。由于文件名改变，上一个版本需要手动合并补丁。

> 直接删掉dnscrypt-proxy的配置文件即可禁用

谢谢，我会尝试
