### ISSUE TITLE
用ternux启用v2ray没用

### ISSUE THREAD

**Issue by leyubook** [Magisk-Modules-Repo/v2ray#77]
用termux显示启用了，但是翻不了，google啥的都打不开

**Comment by leyubook** [comment]
用面具来启动，可以打开google，然后用termux 把v2ray kill掉就上不了网了，怎么回事

**Comment by whyou** [comment]
你用命令行启动和停用都只改变了v2ray的状态，没改变路由表吧？

**Comment by leyubook** [comment]
> 你用命令行启动和取消都只改变了v2ray的状态，没改变路由表吧？

我忘记开起透明代理了，好像还有个小问题，就是没有在migisk里面点击开启那个小倒钩，去termux执行v2ray.service的时候会显示no found

**Comment by whyou** [comment]
> > 你用命令行启动和取消都只改变了v2ray的状态，没改变路由表吧？
> 
> 我忘记开起透明代理了，好像还有个小问题，就是没有在migisk里面点击开启那个小倒钩，去termux执行v2ray.service的时候会显示no found

magisk原理问题
magisk是启动时挂载全部模块，如果取消勾选并重启，则可以认为手机内没有此模块。若勾选后重启，在系统运行中取消勾选，则可找到文件且处于停止状态。

**Comment by leyubook** [comment]
> > > 您用命令行启动和取消都只改变了v2ray的状态，没改变路由表吧？
> > 
> > 
> > 我忘记开起透明代理了，好像还有个小问题，就是没有在migisk里面点击开启那个小倒钩，去termux执行v2ray.service的时候会显示未找到
> 
> magisk原理问题
> magisk是启动时挂载整个模块，如果取消取消并重新启动，则可以认为手机内部没有此模块。若重新开机，在系统运行中取消替换，则可找到文件且处于停止状态。



> > > 您用命令行启动和取消都只改变了v2ray的状态，没改变路由表吧？
> > 
> > 
> > 我忘记开起透明代理了，好像还有个小问题，就是没有在migisk里面点击开启那个小倒钩，去termux执行v2ray.service的时候会显示未找到
> 
> magisk原理问题
> magisk是启动时挂载整个模块，如果取消取消并重新启动，则可以认为手机内部没有此模块。若重新开机，在系统运行中取消替换，则可找到文件且处于停止状态。

好的，谢谢大佬~
