### ISSUE TITLE
I hope to increase the blacklist mode.

### ISSUE THREAD

**Issue by soundghost** [Magisk-Modules-Repo/v2ray#8]
Only some apps do not require a proxy, while other apps pass the proxy.
Because I only have a small amount of software that does not require an agent.
Thank you !

**Comment by chendefine** [comment]
Thanks for reporting, and I think I have already add this feature after https://github.com/Magisk-Modules-Repo/v2ray/issues/2 . Here is the step:
1. Write `# bypass`  at the first line in `/data/v2ray/appid.list`
2. Find those app you don't want to use proxy, and add their uid into `/data/v2ray/appid.list`
3. Restart V2ray Magisk Module.

**Comment by soundghost** [comment]
Thanks !
