### ISSUE TITLE
per application DNS setting

### ISSUE THREAD

**Issue by amosbird** [Magisk-Modules-Repo/v2ray#9]
请问是不是可以加一些rule做到 appid.list 里的应用使用指定的dns而不改变全局dns呢?

**Comment by whyou** [comment]
对于指定app使用特定DNS目前本插件没有这个功能，本插件只是在android上实现v2ray运行以及将所有请求转发到v2ray上实现代理。目前v2ray的处理方式是区分国内国外网址，不知道这种方式对你来说是否可以呢？

**Comment by amosbird** [comment]
哦, 我的v2ray没有配置dns, 不过目前我没有遇到什么问题. 我自己加两条iptables rule 好了
